---
# tasks file for ansible.transmission

- name: Gathering OS specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
      - "{{ ansible_distribution }}.{{ ansible_distribution_release }}.yml"
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      skip: 'true'
  tags: [ 'transmission' ] 

- name: determine transmission package
  set_fact:
    transmission_pkg: "{{ transmission_pkg|default(__transmission_pkg) }}"
  tags: [ 'transmission' ]

- include: install.yml
  tags: [ 'transmission' ]

- include: configure.yml
  tags: [ 'transmission' ]

